defaults:
  - pipeline
  - _self_

onnx_path : ${logs.dir}/model.onnx
batch_size: 1
input_size : ${data.image_size}
export_params : true
input_names: ['input']
output_names: ['output']
dynamic_shapes:
  input :
    0 : 'batch_size'
  output : [0]
opset_version: 16