defaults:
  - pipeline
  - _self_
  - callbacks:
      - model_checkpoint

resume: false
state_dict: ${logs.dir}/pips.pth

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: true

trainer:
  logger: False
  max_epochs: 3
  accelerator: "gpu"
  devices: 1

task:
  learning_rate: 0.1

hydra:
  run:
    dir: ${logs.dir}
