_target_: timm.create_model
model_name: 'convnextv2_large.fcmae_ft_in22k_in1k'
pretrained: true
#
#input_info:
#  require_custom_generation: false
#  inputs:
#    - name: image
#      size:
#        - 1
#        - 3
#        - 224
#        - 224