onnx:
  _target_: benchmark.onnx.OnnxBenchmark
  model_wrapper: ${model_wrapper}
  onnx_path: ${model_paths.onnx}
  device: ${device}
  device_index: 0
  providers:
    - name: "CUDAExecutionProvider"
      parameters:
        arena_extend_strategy: "kSameAsRequested"
    - name: "TensorrtExecutionProvider"
      parameters:
        trt_fp16_enable: true