onnx:
  _target_: benchmark.onnx.OnnxBenchmark
  onnx_path: ${logs.dir}/model.onnx
  device: "cuda"
  device_index: 0
  providers:
    - name: "CUDAExecutionProvider"
      parameters:
        arena_extend_strategy: "kSameAsRequested"
    - name: "TensorrtExecutionProvider"
      parameters:
        trt_fp16_enable: true