model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint

  dirpath: ${logs.dir}/checkpoints
  filename:  '{epoch}-{step}-{train_loss:.2f}'
  monitor: 'train_loss'
  mode : 'min'
  save_last: true
  save_top_k: 3
  every_n_epochs: 1
